### ISSUE TITLE
A.sai.com

### ISSUE THREAD

**Issue by Tassanee14** [python/pythondotorg#2482]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. It would be great if [...]

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/python/pythondotorg/issues/2250
- [ ] https://github.com/python/pythondotorg/issues/2481
- [x] Nate2534@tassanee14.sai.net
```

**Comment by Tassanee14** [comment]
Nate2534@tassanee14.sai.net
