### ISSUE TITLE
Stop using django.contrib.comments

### ISSUE THREAD

**Issue by ubernostrum** [python/pythondotorg#591]
First off, django.contrib.comments is being unbundled from Django and removed in Django 1.8 (and already raises deprecation warnings in Django 1.7). Second, it's overkill for what we're using it for.

Instead, replace it with a simpler model that can live in the jobs app and store the basic information it needs (sender and message, associated with a particular job posting) and use that to handle comments back and forth about job postings.

**Comment by ubernostrum** [comment]
A quick thought:

The basic idea here is that a comment posted on a job will be sent to the set:

```
(jobs moderators + job submitter) - (commenter)
```

But I don't actually know how we distinguish who will have the ability to see, respond to and post moderator-type comments on job submissions waiting for approval. Is there a `Group` instance somewhere for that? Should we create one and specify it in settings?

**Comment by frankwiles** [comment]
Yes there is a 'Job Board Admin' group, see https://github.com/python/pythondotorg/blob/master/jobs/views.py#L12-L13

**Comment by berkerpeksag** [comment]
Current status:
* [x] #981 made `django_comments_xtd` app read-only and added a lightweight commenting implementation
* [x] #1119: Migrate old comments to `JobReviewComment`
* [x] #1121: Remove `django.contrib.comments` and `django_comments_xtd` completely:
  - Remove `django_comments_xtd` from `base-requirements.txt`
  - Remove `COMMENTS_APP = 'django_comments_xtd'`, `'django_comments_xtd'` and `'django.contrib.comments'` from `INSTALLED_APPS` in `pydotorg/settings/base.py`
  - Delete `templates/comments/*`
